name: Test and Coverage

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Type check
        run: npm run type-check
      
      - name: Run tests with coverage
        run: npm run test:coverage
      
      - name: Check coverage threshold
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
            if (( $(echo "$coverage < 100" | bc -l) )); then
              echo "❌ Coverage is below 100%: $coverage%"
              exit 1
            else
              echo "✅ Coverage is at 100%"
            fi
          else
            echo "⚠️ Coverage report not found - tests need to be configured"
          fi

  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "⚠️ requirements.txt not found - backend needs to be configured"
          fi
      
      - name: Run linting
        run: |
          if [ -f requirements.txt ]; then
            pip install ruff
            ruff check app/ || echo "⚠️ Linting needs to be configured"
          fi
      
      - name: Run tests with coverage
        run: |
          if [ -f requirements.txt ] && [ -d tests ]; then
            pytest --cov=app --cov-report=term-missing --cov-fail-under=100
          else
            echo "⚠️ Tests need to be configured"
          fi
      
      - name: Security scan
        run: |
          if [ -f requirements.txt ]; then
            pip install safety
            safety check || echo "⚠️ Security scan needs review"
          fi